version: '3.8'

services:
  # Python Deepfake Detection Service
  detector:
    build:
      context: ./deepfake-detector
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - LOG_LEVEL=info
    volumes:
      - ./deepfake-detector:/app
      - model_cache:/app/models/weights
    networks:
      - deepfake-network
    restart: unless-stopped

  # Node.js Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=development
      - LOCAL_DETECT_URL=http://detector:8001
      - TEMP_PATH=./temp
    volumes:
      - ./backend:/app
      - /app/node_modules
      - temp_files:/app/temp
    networks:
      - deepfake-network
    depends_on:
      - detector
    restart: unless-stopped

  # Next.js Frontend Service
  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - deepfake-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  model_cache:
    driver: local
  temp_files:
    driver: local

networks:
  deepfake-network:
    driver: bridge